[package]
name = "qos"
version = "0.0.1"
edition = "2021"
publish = false

[features]
testexport = []

[dependencies]
bitflags = "1.0.1"
codec = { workspace = true }
kvproto = { git = "https://github.com/pingcap/kvproto.git" }
lazy_static = "1.3"
match-template = "0.0.1"
serde = { version = "1.0", features = ["derive"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
thiserror = "1.0"
tikv_util = { workspace = true }
